"""The ratchet is live: visible debt may hold or fall, never rise (D0020, D0044).

BRIEF §9.1 point 4 says the unenforced count and the Grade-P/S-pending residue "must
trend down". Until M0 that was a flag in the digest; decision D0020 pinned that it
hardens to a `check_decisions` failure at the M0 boundary. These tests are the proof
that it did — a guard nobody has watched fail is a guard nobody knows works.

The poison corpus under `tests/poison/` would be the custodian-visible home for this,
but it is author-key territory (BRIEF §9.1, CLAUDE.md): a builder cannot add a fixture
there. This file is the builder-side equivalent; extending the custodian matrix to the
sub-check is the owner's to do if they want it.
"""

from __future__ import annotations

import datetime as dt
import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts"))

from _gov import Failures, load_yaml, ratchet_metrics  # noqa: E402
from check_decisions import check_ratchet  # noqa: E402

TODAY = dt.date(2026, 9, 1)
DIGEST = """<!-- generated by scripts/gen_projections.py; input-hash: x; DO NOT EDIT BY HAND -->
# Digest — {date}

<!-- metrics: unenforced={unenforced} residue={residue} -->
"""


@pytest.fixture()
def tree(tmp_path: Path) -> Path:
    """The real concept records (so residue is the real number) and an empty digest dir."""
    shutil.copytree(REPO_ROOT / "concepts", tmp_path / "concepts")
    (tmp_path / "digest").mkdir()
    return tmp_path


@pytest.fixture()
def records() -> list[dict]:
    return [load_yaml(p) for p in sorted((REPO_ROOT / "decisions").glob("*.yaml"))]


def write_digest(root: Path, date: str, unenforced: int, residue: int) -> None:
    (root / "digest" / f"{date}.md").write_text(
        DIGEST.format(date=date, unenforced=unenforced, residue=residue), encoding="utf-8"
    )


def check(tree: Path, records: list[dict]) -> Failures:
    fail = Failures("test")
    check_ratchet(tree, TODAY, records, fail)
    return fail


def metrics(tree: Path, records: list[dict]) -> tuple[int, int]:
    return ratchet_metrics(records, [load_yaml(p) for p in sorted((tree / "concepts").glob("*.yaml"))])


def test_no_earlier_digest_means_no_baseline(tree: Path, records: list[dict], capsys) -> None:
    assert not check(tree, records).messages
    assert "no earlier digest to ratchet against" in capsys.readouterr().out


def test_holding_steady_passes(tree: Path, records: list[dict]) -> None:
    write_digest(tree, "2026-08-30", *metrics(tree, records))
    assert not check(tree, records).messages


def test_falling_debt_passes(tree: Path, records: list[dict]) -> None:
    unenforced, residue = metrics(tree, records)
    write_digest(tree, "2026-08-30", unenforced + 3, residue + 1)
    assert not check(tree, records).messages


@pytest.mark.parametrize("metric, phrase", [
    ("unenforced", "unenforced count"),
    ("residue", "Grade-P/S-pending residue"),
])
def test_a_rise_fails_the_guard(tree: Path, records: list[dict], metric: str, phrase: str) -> None:
    unenforced, residue = metrics(tree, records)
    write_digest(
        tree, "2026-08-30",
        unenforced - 1 if metric == "unenforced" else unenforced,
        residue - 1 if metric == "residue" else residue,
    )
    messages = check(tree, records).messages
    assert len(messages) == 1
    assert "RATCHET BREACH" in messages[0] and phrase in messages[0]


def test_the_baseline_ignores_a_digest_written_today(tree: Path, records: list[dict]) -> None:
    """Regenerating today's digest cannot launder a rise: the baseline is strictly
    older than today, so the rise must appear in a digest the owner sees first."""
    unenforced, residue = metrics(tree, records)
    write_digest(tree, "2026-08-30", unenforced - 1, residue)
    write_digest(tree, TODAY.isoformat(), unenforced, residue)
    assert check(tree, records).messages


def test_the_guard_is_wired_into_the_real_check() -> None:
    """A guard that exists but is never called is not a guard.

    The nested marker is set deliberately: this very file is a pytest binding target, so
    without it the child would resolve bindings by running this file, which would run
    this test, for ever. The child still performs the ratchet check — that is what is
    being asserted.
    """
    result = subprocess.run(
        [sys.executable, "scripts/check_decisions.py"],
        cwd=REPO_ROOT, capture_output=True, text=True, check=False,
        env={**os.environ, "TANNEN_CHECK_DECISIONS_NESTED": "1"},
    )
    assert "ratchet:" in result.stdout, result.stdout + result.stderr
    # RT-08: unchecked bindings must never be described as green. The "NOT RESOLVED"
    # line prints whatever else the run concludes; the "green" phrasing must never
    # appear in a run that resolved nothing. Asserting the OK-summary wording instead
    # would make this test fail for any unrelated violation, which is a worse test.
    assert "NOT RESOLVED (nested run" in result.stdout
    assert "binding(s) green" not in result.stdout
