"""Shared helpers for the governance scripts. Not part of the kernel; IO is its job."""

from __future__ import annotations

import datetime as dt
import hashlib
import json
import os
import re
import subprocess
import sys
from pathlib import Path

import jsonschema
import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent

GEN_MARKER = "generated by scripts/gen_projections.py"

#: The machine-readable ratchet line every digest carries (BRIEF §9.1 point 4).
METRICS_RE = re.compile(r"<!-- metrics: unenforced=(\d+) residue=(\d+) -->")

# Milestone-boundary tags = owner sittings (BRIEF §8, §9.1 cadence).
BOUNDARY_TAG_RE = re.compile(r"^(brief-freeze|.+-laws-freeze|.+-close)$")


#: Git environment variables that override repository discovery. A git hook runs with
#: GIT_DIR (and friends) exported, and they beat `git -C <path>` — so a guard invoked
#: from pre-commit, or pointed at a poison fixture, would silently answer about the
#: WRONG repository. Every helper here that names a repo strips them first.
GIT_LOCATION_VARS = (
    "GIT_DIR", "GIT_WORK_TREE", "GIT_INDEX_FILE", "GIT_COMMON_DIR",
    "GIT_OBJECT_DIRECTORY", "GIT_ALTERNATE_OBJECT_DIRECTORIES", "GIT_NAMESPACE",
    "GIT_PREFIX",
)


def git_env(extra: dict[str, str] | None = None) -> dict[str, str]:
    """os.environ minus the location overrides, so `git -C <path>` means what it says."""
    env = {k: v for k, v in os.environ.items() if k not in GIT_LOCATION_VARS}
    if extra:
        env.update(extra)
    return env


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_file(path: Path) -> str:
    return sha256_bytes(path.read_bytes())


def load_yaml(path: Path) -> object:
    with path.open("r", encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def load_schema(root: Path, name: str) -> dict:
    """Load a governance schema from root; fall back to the real repo's frozen schema
    when the root (a poison fixture tree, tests/poison/) does not carry its own —
    poison trees must violate a guard, not duplicate the frozen schemas."""
    candidate = root / "governance" / "schemas" / name
    if not candidate.exists():
        candidate = REPO_ROOT / "governance" / "schemas" / name
    return json.loads(candidate.read_text(encoding="utf-8"))


def schema_errors(instance: object, schema: dict) -> list[str]:
    validator = jsonschema.Draft202012Validator(schema)
    return [
        f"{'/'.join(str(p) for p in e.absolute_path) or '<root>'}: {e.message}"
        for e in validator.iter_errors(instance)
    ]


def parse_manifest(path: Path) -> dict[str, str]:
    """Parse sha256sum-format lines ('<hash>  <path>') into {path: hash}."""
    entries: dict[str, str] = {}
    for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split(maxsplit=1)
        if len(parts) != 2 or len(parts[0]) != 64:
            raise ValueError(f"{path.name}:{lineno}: not a sha256sum line: {line!r}")
        entries[parts[1].strip()] = parts[0]
    return entries


def input_hash(paths: list[Path], root: Path) -> str:
    """Deterministic hash over a set of input files: sorted (relpath, sha256) pairs."""
    pairs = sorted((str(p.relative_to(root)), sha256_file(p)) for p in paths)
    payload = "\n".join(f"{h}  {rel}" for rel, h in pairs).encode("utf-8")
    return sha256_bytes(payload)


def read_header_hash(path: Path) -> str | None:
    """Extract the input-hash from a generated projection's header comment."""
    if not path.exists():
        return None
    first = path.read_text(encoding="utf-8").splitlines()[:1]
    if not first or GEN_MARKER not in first[0] or "input-hash: " not in first[0]:
        return None
    tail = first[0].split("input-hash: ", 1)[1]
    return tail.split(";", 1)[0].split(" ", 1)[0].strip()


def ratchet_metrics(records: list[dict], concepts: list[dict]) -> tuple[int, int]:
    """The two ratcheted metrics (BRIEF §9.1): unenforced decisions, Grade-P/S-pending
    residue. One definition, read by the generator that reports them and the guard that
    enforces them — two definitions would be two answers."""
    unenforced = sum(1 for r in records if not r["bindings"])
    residue = sum(1 for c in concepts if c["grade"] in ("P", "S-pending"))
    return unenforced, residue


def binding_strengths(records: list[dict]) -> tuple[int, int]:
    """(enforced, documentary) binding counts (decision D0052).

    A binding either prevents or detects a violation, or it merely records that someone
    meant to. `binding_violation` cannot tell the difference — it asks whether a target
    exists, resolves or passes — so a drafted proposal awaiting the owner's key counts
    exactly like a frozen path. Absent `strength` reads as `enforced`, so records written
    before the field existed keep their meaning; the number is only true once the batch
    they belong to has been marked, which is why the ratchet must not compare it until a
    digest has carried honest values once (the sequencing hazard in the proposal).
    """
    enforced = documentary = 0
    for record in records:
        for binding in record.get("bindings") or []:
            if binding.get("strength", "enforced") == "documentary":
                documentary += 1
            else:
                enforced += 1
    return enforced, documentary


def previous_metrics(root: Path, today: dt.date) -> tuple[str, int, int] | None:
    """(date, unenforced, residue) from the most recent digest STRICTLY OLDER than today.

    Strictly older on purpose: if today's own digest counted, a session could raise the
    debt and then regenerate the baseline in the same breath. Excluding it means a rise
    must first appear in a digest the owner sees, flagged, before it can become the
    number the next session is measured against.
    """
    digests = sorted(p for p in (root / "digest").glob("*.md") if p.stem < today.isoformat())
    for path in reversed(digests):
        match = METRICS_RE.search(path.read_text(encoding="utf-8"))
        if match:
            return path.stem, int(match.group(1)), int(match.group(2))
    return None


def custody_declaration(root: Path) -> dict:
    """The `custody` block of governance/tier-c.yaml, or {} if there is none.

    A root without the file is a poison fixture or a pre-governance tree, not an error:
    check_tier_c_consistency reports the absence. Crashing here would replace another
    guard's clean marker with a traceback (the same defect check_sealed_paths had).
    """
    tier_c_path = root / "governance" / "tier-c.yaml"
    if not tier_c_path.exists():
        return {}
    tier_c = load_yaml(tier_c_path)
    if not isinstance(tier_c, dict):
        return {}
    declared = tier_c.get("custody")
    return declared if isinstance(declared, dict) else {}


def custody_rows(root: Path) -> tuple[list[str], list[str]]:
    """(rows, problems) — the exact intended content of the custody file.

    The custody set is a POSITIVE enumeration of the bytes the owner vouches for, which
    is what MANIFEST.sha256 is not: the manifest is a whitelist of hashes that says
    nothing about what it should contain, so a row can be deleted and the path silently
    unfreezes (RT-01). A pattern matching nothing is therefore a hole in the set, not an
    empty set, and is reported as a problem rather than skipped.
    """
    patterns = custody_declaration(root).get("set") or []
    seen: dict[str, str] = {}
    problems: list[str] = []
    for pattern in patterns:
        matches = [
            path for path in sorted(root.glob(pattern))
            if path.is_file() and "__pycache__" not in path.parts
        ]
        if not matches:
            problems.append(
                f"custody pattern matches nothing: {pattern} — a pattern that matches no "
                "file is a hole in the custody set, not an empty set"
            )
            continue
        for path in matches:
            seen[path.relative_to(root).as_posix()] = sha256_file(path)
    return [f"{seen[rel]}  {rel}" for rel in sorted(seen)], problems


def resolve_dotted(obj: object, dotted: str) -> object:
    """Resolve 'a.b.c' through nested mappings; raises KeyError on a miss."""
    cur = obj
    for part in dotted.split("."):
        if not isinstance(cur, dict) or part not in cur:
            raise KeyError(dotted)
        cur = cur[part]
    return cur


def boundary_tag_dates(root: Path) -> list[dt.date]:
    """Creation dates of milestone-boundary tags, oldest first; [] outside a git repo."""
    try:
        out = subprocess.run(
            ["git", "-C", str(root), "tag", "-l", "--format=%(refname:short) %(creatordate:short)"],
            capture_output=True, text=True, check=True, env=git_env(),
        ).stdout
    except (OSError, subprocess.CalledProcessError):
        return []
    dates = []
    for line in out.splitlines():
        parts = line.rsplit(" ", 1)
        if len(parts) == 2 and BOUNDARY_TAG_RE.match(parts[0]):
            try:
                dates.append(dt.date.fromisoformat(parts[1]))
            except ValueError:
                pass
    return sorted(dates)


def owner_key_enrolled(root: Path) -> bool:
    """True iff allowed_signers carries a non-comment owner@tannen key line."""
    signers = root / "allowed_signers"
    if not signers.exists():
        return False
    return any(
        line.split() and line.split()[0] == "owner@tannen"
        for line in signers.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    )


def receipt_state(root: Path, today: dt.date) -> tuple[bool, str]:
    """Attention-receipt freshness (BRIEF §9.1): the latest author-signed receipt is
    fresh until 7 days after the first milestone boundary that follows it. Stale (or
    absent, or unverifiable) means Tier-B silence-as-consent is suspended."""
    receipts = []
    receipts_dir = root / "receipts"
    if receipts_dir.is_dir():
        for path in receipts_dir.glob("*.md"):
            try:
                receipts.append((dt.date.fromisoformat(path.stem), path))
            except ValueError:
                pass
    if not receipts:
        return False, "no attention receipt exists yet (first receipt lands at the opening sitting)"
    rdate, latest = max(receipts)
    sig = latest.with_name(latest.name + ".sig")
    if not owner_key_enrolled(root):
        return False, "no owner key enrolled in allowed_signers, so no receipt can verify"
    if not sig.exists():
        return False, f"latest receipt {latest.name} is unsigned"
    verify = subprocess.run(
        ["ssh-keygen", "-Y", "verify", "-f", str(root / "allowed_signers"),
         "-I", "owner@tannen", "-n", "tannen-receipt", "-s", str(sig)],
        input=latest.read_bytes(), capture_output=True,
    )
    if verify.returncode != 0:
        return False, f"receipt {latest.name} signature does not verify against owner@tannen"
    later = [d for d in boundary_tag_dates(root) if d > rdate]
    if not later:
        return True, f"receipt {latest.name} fresh (no milestone boundary since)"
    valid_until = later[0] + dt.timedelta(days=7)
    if today <= valid_until:
        return True, f"receipt {latest.name} fresh until {valid_until} (boundary {later[0]} + 7d)"
    return False, f"receipt {latest.name} stale: boundary {later[0]} + 7 days elapsed"


def effective_status(record: dict, today: dt.date, receipts_fresh: bool) -> str:
    """Computed status: veto lapse converts to acceptance only under a fresh receipt
    (BRIEF §9.1); records themselves are append-only and never edited to say so."""
    if record["tier"] == "B" and record["status"] == "provisional":
        if dt.date.fromisoformat(record["veto_by"]) < today:
            if receipts_fresh:
                return "accepted (veto lapsed)"
            return "provisional — BLOCKED (veto window passed, attention receipt stale)"
    return record["status"]


class Failures:
    """Collects violations; exits non-zero if any were recorded."""

    def __init__(self, script: str) -> None:
        self.script = script
        self.messages: list[str] = []

    def add(self, msg: str) -> None:
        self.messages.append(msg)

    def finish(self, ok_msg: str) -> int:
        if self.messages:
            print(f"{self.script}: FAIL ({len(self.messages)} violation(s))", file=sys.stderr)
            for msg in self.messages:
                print(f"  - {msg}", file=sys.stderr)
            return 1
        print(f"{self.script}: OK — {ok_msg}")
        return 0
