#!/usr/bin/env python3
"""gen_roadmap.py — ROADMAP.md, a generated projection of open work by who can close it.

WHY THIS EXISTS. The digest's "Requires owner" section is a query over Tier-C records
only (gen_projections.py, `if rec["tier"] != "C": continue`), and the boundary sitting
driver filters the same way. But BRIEF §9.2 defines tiers by REVERSIBILITY, not by
custody: a fully reversible Tier-A decision whose artifact is custody-set still needs the
owner's key. Every such item is therefore invisible in the one section the owner is
committed to reading. That blindness cost a milestone three times (D0154, D0191, D0195),
and D0214/D0215 were both filed Tier C to dodge it rather than because Tier C fit.

THE INPUT CONTRACT (D0215). Every byte of this file derives from files in the same
commit. This generator may NOT shell out to git, read the clock, or call any _gov helper
that takes `today` (receipt_state, effective_status, previous_metrics) or reads refs
(boundary_tag_dates). D0215 measured what happens otherwise: DECISIONS.md embeds a
verdict computed from `git tag -l` and from today's date, so every close tag now points
at a commit that fails `make verify`, and the history is green only near the tip. A
`--today` argument is accepted here and deliberately ignored; a test proves it inert.

THREE PROVENANCES, AND NO FOURTH. Every line is either CITED (a path plus the sha256 of a
frozen file), EXTRACTED (bytes copied verbatim from a named frozen file at generation
time) or QUERIED (computed from structured fields). There is no hand-written content
channel — no notes file, no prose YAML. If there is nowhere to type, there is nothing to
rot. A reader who wants to add to the roadmap must file a decision record.
"""

from __future__ import annotations

import argparse
import datetime as dt
import sys
from pathlib import Path

# Run under `python -I -P` (conferral ruling 3, D0063), as every other generator here
# does: isolated mode ignores PYTHONPATH and user site-packages, and -P stops any
# directory being prepended to sys.path implicitly — including this script's own.
sys.path.insert(0, str(Path(__file__).resolve().parent))

from _gov import (  # noqa: E402
    binding_strengths,
    input_hash,
    load_yaml,
    parse_manifest,
    ratchet_metrics,
    REPO_ROOT,
    sha256_file,
)

# Duplicated from _gov deliberately, and this is the one duplication in the file.
# _gov.GEN_MARKER and _gov.read_header_hash hard-code the *projections* marker, and
# scripts/_gov.py is custody-set — a builder may not add a second constant there. So the
# marker and its parser live here, defined once, and the test imports them from here
# rather than re-spelling them. Two spellings would be two answers (_gov.ratchet_metrics'
# own docstring makes the argument).
ROADMAP_MARKER = "generated by scripts/gen_roadmap.py"

SEALED_NOTE = "sealed"
FROZEN_NOTE = "frozen"
CUSTODY_NOTE = "custody-set"


def read_roadmap_header(path: Path) -> str | None:
    """Extract the input-hash from ROADMAP.md's header comment."""
    if not path.exists():
        return None
    first = path.read_text(encoding="utf-8").splitlines()[:1]
    if not first or ROADMAP_MARKER not in first[0] or "input-hash: " not in first[0]:
        return None
    tail = first[0].split("input-hash: ", 1)[1]
    return tail.split(";", 1)[0].split(" ", 1)[0].strip()


def roadmap_inputs(root: Path) -> list[Path]:
    """Every file this generator reads. Public because the test parameterises over it.

    Derived from globs, never hand-listed: a hand-maintained enumeration is the failure
    class this repo forbids for guards. A test appends a byte to each of these in turn
    and asserts the input hash moves, so a member that stops being load-bearing is
    reported rather than quietly carried.
    """
    singles = [
        root / "BRIEF.md",
        root / "MANIFEST.sha256",
        root / ".pre-commit-config.yaml",
        root / "governance" / "custody.sha256",
        root / "governance" / "policy.yaml",
        root / "governance" / "tier-c.yaml",
    ]
    globbed = (
        sorted((root / "decisions").glob("*.yaml"))
        + sorted((root / "decisions").glob("*.yaml.sig"))
        + sorted((root / "concepts").glob("*.yaml"))
    )
    return [p for p in singles if p.exists()] + globbed


def rel(path: Path, root: Path) -> str:
    """Repo-relative POSIX path. Never an absolute one: tests/test_no_pii.py scans every
    tracked file for home-directory paths, and this artifact is tracked."""
    return path.relative_to(root).as_posix()


def gist(text: str, limit: int = 160) -> str:
    """First sentence-ish, truncated on a word boundary with a visible ellipsis."""
    flat = " ".join(text.split())
    if len(flat) <= limit:
        return flat
    return flat[:limit].rsplit(" ", 1)[0] + " …"


def brief_section_8(root: Path) -> str:
    """EXTRACT BRIEF §8's arc paragraph. Never restate it.

    BRIEF.md is frozen AND custody-set, so it cannot drift without check_manifest and
    check_custody both failing first — which is what makes copying its bytes safe here
    and would make copying an unfrozen file's bytes unsafe. Restating it in prose is the
    rot this project was bitten by three times in one milestone (ci.yml's "the repo has
    no remote" header; D0191's false freeze claim; docs/specs/m3.md §7).
    """
    lines = (root / "BRIEF.md").read_text(encoding="utf-8").splitlines()
    start = next((i for i, ln in enumerate(lines) if ln.startswith("## 8. ")), None)
    if start is None:
        sys.exit("gen_roadmap: BRIEF.md has no '## 8. ' heading — refusing to guess")
    body = []
    for ln in lines[start + 1:]:
        if ln.startswith("## "):
            break
        if ln.strip():
            body.append(ln.strip())
        elif body:
            break
    if not body:
        sys.exit("gen_roadmap: BRIEF.md §8 extracted empty — refusing to emit a hole")
    return " ".join(body)


def owner_held(root: Path) -> tuple[dict[str, str], set[str]]:
    """({path: why a builder may not write it}, sealed dir prefixes).

    Three separate seals, and they mean different things: MANIFEST.sha256 freezes bytes,
    governance/custody.sha256 is the owner's positive vouching set, and tier-c.yaml's
    sealed_dirs require every file beneath them to carry a manifest row.
    """
    frozen = set(parse_manifest(root / "MANIFEST.sha256"))
    custody = set(parse_manifest(root / "governance" / "custody.sha256"))
    tier_c = load_yaml(root / "governance" / "tier-c.yaml") or {}
    sealed = set((tier_c.get("frozen_paths") or {}).get("sealed_dirs") or [])

    held: dict[str, str] = {}
    for path in sorted(frozen | custody):
        why = [FROZEN_NOTE] if path in frozen else []
        if path in custody:
            why.append(CUSTODY_NOTE)
        if any(path.startswith(d + "/") for d in sealed):
            why.append(SEALED_NOTE)
        held[path] = ", ".join(why)
    return held, sealed


def binding_target_path(target: str) -> str:
    """The file a binding names, stripped of '#dotted.key' and '::pytest::node'."""
    return target.split("#", 1)[0].split("::", 1)[0].strip()


def load_records(root: Path) -> list[tuple[Path, dict]]:
    return [(p, load_yaml(p)) for p in sorted((root / "decisions").glob("*.yaml"))]


def is_signed(path: Path) -> bool:
    """A decision record has a sibling .sig iff a builder may not edit its bytes.

    D0214 measured the consequence: the signature is over the record's whole bytes, so
    changing one of its bindings invalidates it. That turns "who may apply this" from a
    judgement into a Path.exists().
    """
    return path.with_name(path.name + ".sig").exists()


def regeneration_sentence(root: Path) -> str:
    """DERIVED, not typed, so it corrects itself when the owner wires the hook.

    Reads .pre-commit-config.yaml for a hook that names this generator. That is a config
    lookup, not prose-reading: the file is already an input and the check is a substring
    of a hook `entry`, which is a key's value.
    """
    cfg = (root / ".pre-commit-config.yaml").read_text(encoding="utf-8")
    if "gen_roadmap.py" in cfg:
        return (
            "A pre-commit hook regenerates this file, so a stale copy cannot be "
            "committed."
        )
    return (
        "**Nothing regenerates this file automatically.** `.pre-commit-config.yaml` and "
        "`Makefile` are both custody-set, so the builder who added this generator could "
        "not add the hook that runs it. Until the owner does, every commit that adds a "
        "decision record leaves this file stale until someone runs the command above by "
        "hand — and a stale copy makes `check_decisions`' batched pytest resolution fall "
        "back to one invocation per binding target."
    )


def section_arc(root: Path) -> list[str]:
    manifest = parse_manifest(root / "MANIFEST.sha256")
    brief_hash = manifest.get("BRIEF.md", sha256_file(root / "BRIEF.md"))
    policy = load_yaml(root / "governance" / "policy.yaml") or {}
    envelopes = policy.get("budget_envelopes") or {}

    out = [
        "## 1. The arc",
        "",
        "Extracted verbatim from `BRIEF.md` §8, which is frozen and custody-set — it "
        f"cannot change without two guards failing first. sha256 `{brief_hash[:12]}`.",
        "",
        f"> {brief_section_8(root)}",
        "",
        "Milestones carrying a spend envelope (`governance/policy.yaml`, owner-signed):",
        "",
        "| Milestone | Envelope (USD) |",
        "|---|---|",
    ]
    out += [f"| {k} | {v} |" for k, v in envelopes.items()]
    out += [
        "",
        "Raising any of these is Tier-C door 1, and BRIEF §9.1 makes a dedicated owner "
        "sitting the gate for M4 specifically, before any nonzero budget.",
        "",
    ]
    return out


def section_build(root: Path) -> list[str]:
    """Per-milestone artifact presence, from MANIFEST.sha256 rows alone.

    Deliberately NO "closed?" column. Whether a milestone's close tag has been minted
    lives in a tag, and a tag is not in a commit — putting it here would be a fresh
    instance of D0215, in the artifact filed to record D0215.
    """
    manifest = parse_manifest(root / "MANIFEST.sha256")
    # `m<digits>` only. docs/specs/ also holds forward-correction files such as
    # m3-corrections.md, and tests/laws/ holds evidence-vectors/ — neither is a
    # milestone, and a looser match silently invents one.
    is_milestone = lambda name: name.startswith("m") and name[1:].isdigit()  # noqa: E731
    specs = {p.split("/")[-1][:-3]: h for p, h in manifest.items()
             if p.startswith("docs/specs/") and p.endswith(".md")}
    law_rows: dict[str, int] = {}
    for path in manifest:
        if path.startswith("tests/laws/"):
            milestone = path.split("/")[2]
            law_rows[milestone] = law_rows.get(milestone, 0) + 1

    milestones = sorted(
        {m for m in law_rows if is_milestone(m)} | {s for s in specs if is_milestone(s)},
        key=lambda m: int(m[1:]),
    )
    out = [
        "## 2. Where the build is",
        "",
        "Milestone artefacts, counted from `MANIFEST.sha256` rows. A milestone's laws are "
        "frozen when its spec and its `tests/laws/<m>/` rows are both present.",
        "",
        "| Milestone | Frozen spec | Frozen law-file rows |",
        "|---|---|---|",
    ]
    for m in milestones:
        spec = f"`docs/specs/{m}.md` `{specs[m][:12]}`" if m in specs else "**absent**"
        out.append(f"| {m} | {spec} | {law_rows.get(m, 0)} |")
    out += [
        "",
        "*Not shown, deliberately:* whether each milestone's close tag exists, and law "
        "evidence freshness. The first lives in a git tag and the second in the "
        "gitignored `evidence/` store; neither is in this commit, and embedding either "
        "would reproduce D0215's defect here. For evidence, run `uv run tannen laws "
        "report`, which is regenerated per run and never compared against a later "
        "recomputation.",
        "",
    ]
    return out


def section_owner_queue(root: Path) -> list[str]:
    out = [
        "## 3. The owner queue — every tier",
        "",
        "Every record recorded `blocked-on-owner`, **at any tier**. This is not a tier "
        "query, and that is the point: BRIEF §9.2 classifies tiers by reversibility, so a "
        "fully reversible Tier-A decision whose artifact is custody-set still needs the "
        "owner's key. `digest/<date>.md` filters `tier == \"C\"` and cannot see it "
        "(D0154, D0191, D0195, D0214).",
        "",
        "| Record | Tier | Signed | Ask |",
        "|---|---|---|---|",
    ]
    rows = [
        f"| {rec['id']} | {rec['tier']} | "
        f"{'owner-signed' if is_signed(path) else 'unsigned'} | "
        f"{gist(rec.get('title', ''))} |"
        for path, rec in load_records(root)
        if rec.get("status") == "blocked-on-owner"
    ]
    out += rows or ["| — | — | — | *(nothing recorded)* |"]
    out += [
        "",
        f"{len(rows)} open. An empty or thin queue means nobody recorded one, not that "
        "none exists — see §8.",
        "",
    ]
    return out


def section_owner_artifacts(root: Path) -> list[str]:
    """Artifact-keyed census. NOT a to-do list, and it says so."""
    held, _ = owner_held(root)
    by_path: dict[str, list[str]] = {}
    for path, rec in load_records(root):
        for binding in rec.get("bindings") or []:
            if binding.get("strength") != "documentary":
                continue
            target = binding_target_path(binding.get("target", ""))
            if target in held:
                by_path.setdefault(target, []).append(rec["id"])

    out = [
        "## 4. Owner-held artefacts that records point at",
        "",
        "Grouped by artefact, not by record. A `documentary` binding records intent and "
        "detects nothing, and it has two causes no guard can tell apart: a drafted change "
        "awaiting the owner's key, and a permanent citation into a file that will never "
        "change. The discriminator is in each binding's prose, and no test here may learn "
        "another artefact's state that way (D0213). **This is a census, never a to-do "
        "list.**",
        "",
        "| Artefact | Seal | Records |",
        "|---|---|---|",
    ]
    for target in sorted(by_path, key=lambda t: (-len(by_path[t]), t)):
        ids = sorted(set(by_path[target]))
        out.append(f"| `{target}` | {held[target]} | {len(ids)}: {', '.join(ids)} |")
    out.append("")
    return out


def section_understated(root: Path) -> list[str]:
    """The one exact, zero-judgement query: a file binding on an already-frozen path."""
    frozen = set(parse_manifest(root / "MANIFEST.sha256"))
    rows = []
    for path, rec in load_records(root):
        for binding in rec.get("bindings") or []:
            if binding.get("type") != "file" or binding.get("strength") != "documentary":
                continue
            target = binding_target_path(binding.get("target", ""))
            if target in frozen:
                rows.append(
                    f"| {rec['id']} | {rec['tier']} | `{target}` | "
                    f"{'owner — re-signature' if is_signed(path) else 'builder'} |"
                )
    out = [
        "## 5. Bindings that understate their enforcement",
        "",
        "A `type: file` binding marked `documentary` whose target is **already** in "
        "`MANIFEST.sha256`. A `type: manifest` binding on that same target would resolve "
        "today and would detect an unfreeze, so the type upgrade is mechanically correct "
        "whatever the reason for the strength. D0214 found nine of these by hand across "
        "five records; this is the general query.",
        "",
        "Records carrying a sibling `.sig` cannot be upgraded by a builder: the signature "
        "is over the record's whole bytes, so editing a binding invalidates it (D0214).",
        "",
        "| Record | Tier | Target | Who can apply |",
        "|---|---|---|---|",
    ]
    out += rows or ["| — | — | — | *(none)* |"]
    out += ["", f"{len(rows)} binding(s).", ""]
    return out


def section_builder_debt(root: Path) -> list[str]:
    records = [rec for _, rec in load_records(root)]
    unenforced = [r for r in records if not r.get("bindings")]
    provisional = [r for r in records if r.get("status") == "provisional"]
    out = [
        "## 6. Builder debt",
        "",
        f"Records with no binding at all: **{len(unenforced)}**"
        + ("" if not unenforced else " — " + ", ".join(r["id"] for r in unenforced)),
        "",
        f"Records still `provisional`: **{len(provisional)}**.",
        "",
    ]
    if provisional:
        out += ["| Record | veto_by | Title |", "|---|---|---|"]
        out += [
            f"| {r['id']} | {r.get('veto_by', '—')} | {gist(r.get('title', ''), 90)} |"
            for r in provisional
        ]
        out += [
            "",
            "*Dates, not countdowns.* Whether a veto has lapsed into consent depends on "
            "today and on attention-receipt freshness, and neither is in this commit "
            "(D0215). `DECISIONS.md` computes the effective status; this file records "
            "what the record says.",
            "",
        ]
    return out


def section_counts(root: Path) -> list[str]:
    records = [rec for _, rec in load_records(root)]
    concepts = [load_yaml(p) for p in sorted((root / "concepts").glob("*.yaml"))]
    unenforced, residue = ratchet_metrics(records, concepts)
    enforced, documentary = binding_strengths(records)

    tiers: dict[str, int] = {}
    for rec in records:
        tiers[rec["tier"]] = tiers.get(rec["tier"], 0) + 1
    types: dict[str, int] = {}
    for rec in records:
        for binding in rec.get("bindings") or []:
            types[binding["type"]] = types.get(binding["type"], 0) + 1

    return [
        "## 7. Counts",
        "",
        f"- Records: **{len(records)}** ("
        + ", ".join(f"Tier {t}: {n}" for t, n in sorted(tiers.items())) + ")",
        f"- Bindings: **{enforced} enforced**, **{documentary} documentary** ("
        + ", ".join(f"{t}: {n}" for t, n in sorted(types.items())) + ")",
        f"- Unenforced records: **{unenforced}**",
        f"- Grade-P / S-pending concept residue: **{residue}**",
        "",
        "*No trend.* `previous_metrics` selects the newest digest strictly older than "
        "today, so a delta moves with the clock. The trend lives in `digest/<date>.md`, "
        "which is dated and never recompared (D0215).",
        "",
    ]


def section_blind_spots(root: Path) -> list[str]:
    return [
        "## 8. What this cannot see",
        "",
        "1. **An owner item nobody recorded.** §3 has exactly one handle — the `status` "
        "field. A record filed Tier A / `accepted` whose remaining work needs the owner's "
        "key is invisible, and several exist today: D0197 and D0198 both carry only "
        "`enforced` bindings on builder-writable paths while naming owner work in their "
        "prose, and D0212's relocation binds to nothing at all, deliberately — a binding "
        "that cannot resolve in a fresh clone is a broken guard. This file creates a "
        "place where recording such an item pays off; it cannot find what nobody recorded.",
        "2. **A finished item nobody closed.** Nothing distinguishes a `blocked-on-owner` "
        "record whose work is done from one whose is not. It will be listed for ever.",
        "3. **Why a binding is documentary** (§4) — pending versus permanent is prose.",
        "4. **Tags, dates, receipt freshness and law evidence** — none is in this commit, "
        "and all four are excluded on purpose (D0215).",
        "5. **Not a blind spot, but a latency.** A hand edit here *is* caught: "
        "`tests/test_roadmap.py::test_roadmap_is_fresh` compares this file byte for byte "
        "against a fresh render, which is strictly stronger than the input-hash header "
        "`CONCEPTS.md` relies on (a hash in a header cannot see an edit to the body). "
        "What is missing is not detection but repair — no hook regenerates this file, so "
        "the mismatch surfaces at `make verify`, minutes after the change that caused it, "
        "instead of being fixed in place at commit time.",
        "",
    ]


def section_sources(root: Path, inputs: list[Path]) -> list[str]:
    out = [
        "## 9. Sources",
        "",
        "Every file read, with the hash that went into the header. Individual "
        "`decisions/*.yaml`, `decisions/*.yaml.sig` and `concepts/*.yaml` members are "
        "summarised by count; the header hash covers each one.",
        "",
        "| Input | sha256 |",
        "|---|---|",
    ]
    grouped: dict[str, int] = {}
    for path in inputs:
        relpath = rel(path, root)
        if relpath.startswith(("decisions/", "concepts/")):
            key = relpath.rsplit("/", 1)[0] + "/" + (
                "*.yaml.sig" if relpath.endswith(".sig") else "*.yaml")
            grouped[key] = grouped.get(key, 0) + 1
        else:
            out.append(f"| `{relpath}` | `{sha256_file(path)[:12]}` |")
    out += [f"| `{k}` | *{n} file(s)* |" for k, n in sorted(grouped.items())]
    out.append("")
    return out


def render(root: Path, today: dt.date | None = None) -> str:
    """Render ROADMAP.md.

    `today` is accepted and IGNORED. The parameter exists so a test can prove it inert
    by rendering under two wildly different dates and asserting byte-equality — a
    parameter proven not to matter is a stronger claim than one that was never offered.
    """
    del today
    inputs = roadmap_inputs(root)
    body = [
        f"<!-- {ROADMAP_MARKER}; input-hash: {input_hash(inputs, root)}; "
        "DO NOT EDIT BY HAND -->",
        "# ROADMAP — open work, by who can close it (generated projection)",
        "",
        "A query over `decisions/*.yaml` and the seal files, not a plan anyone typed. "
        "There is no hand-written channel in this document: to add something to it, file "
        "a decision record.",
        "",
        "Regenerate with `.venv/bin/python -I -P scripts/gen_roadmap.py`. "
        + regeneration_sentence(root),
        "",
        "Nothing here varies with the clock or with the tag set, and that is a "
        "requirement rather than an omission — see §8 and D0215.",
        "",
    ]
    body += section_arc(root)
    body += section_build(root)
    body += section_owner_queue(root)
    body += section_owner_artifacts(root)
    body += section_understated(root)
    body += section_builder_debt(root)
    body += section_counts(root)
    body += section_blind_spots(root)
    body += section_sources(root, inputs)
    return "\n".join(body).rstrip("\n") + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=REPO_ROOT)
    parser.add_argument("--today", type=dt.date.fromisoformat, default=None,
                        help="accepted and ignored; output is clock-independent (D0215)")
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if ROADMAP.md is stale; write nothing")
    args = parser.parse_args()

    root = args.root.resolve()
    content = render(root, args.today)
    out = root / "ROADMAP.md"

    if args.check:
        if not out.exists() or out.read_text(encoding="utf-8") != content:
            print("ROADMAP.md is stale — run "
                  ".venv/bin/python -I -P scripts/gen_roadmap.py", file=sys.stderr)
            return 1
        print("gen_roadmap: ROADMAP.md is fresh")
        return 0

    if out.exists() and out.read_text(encoding="utf-8") == content:
        print("gen_roadmap: ROADMAP.md unchanged")
    else:
        out.write_text(content, encoding="utf-8")
        print("gen_roadmap: regenerated ROADMAP.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
